version: '3'
services:
  vue:
    build: ./vue
    ports:
      - 8080:8080
    volumes:
      - ./app:/usr/src/app
    stdin_open: true
    tty: true
    command: /bin/sh
  php:
    build:
      context: ./php
      dockerfile: dockerfile
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php:/var/www/html
    ports:
      - 9050:80
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    command: --innodb-use-native-aio=0